options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/student-00332/my-repo/flask_service:latest',
        '.'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/student-00332/my-repo/flask_service:latest'
      ]

images:
  - 'us-central1-docker.pkg.dev/student-00332/my-repo/flask_service:latest'
